### PR TITLE
chore(translate): update german

### PR DESCRIPTION
**Pull request by madeddy**
Add missing strings for german tl

### CODE REVIEW

**Comment by orblazer** [comment]
Hello, thanks for your update.

I go to keep that PR open until i'm certain of the translation no longer changed.
I give me the end of week to finish to check everything and finish to prepare deployment, so i will notice you here when that release is fully frozen to update with last changes.

Thanks.

**Comment by madeddy** [comment]
All right. Thanks for your work! 👍🏻

**Comment by orblazer** [comment]
Hello,
The change as been frozen, so you are free to update it before the release.

Thanks.

**Comment by madeddy** [comment]
Hey, i am done. 
Greets

**Review by orblazer — CHANGES_REQUESTED** [review]
Could you create an new PR, or tel me if i can simply co commit your changes to prevent "Merge" commits ?

Also the old lines (on bottom of file) should be removed.

**Comment by madeddy** [comment]
>  if i can simply co commit

That's alright. Do that-

>  could you have the commit following "conventional-commit", so the commit name should something like `chore(translate): update dutch`

Sorry, nut i don't understand the meaning of this line. I changed the PR title. Was this the intend?

**Comment by orblazer** [comment]
I close the PR in favor of #79.

> Sorry, but i don't understand the meaning of this line. I changed the PR title. Was this the intend?

This is about the commit message (like the one i have make in the new PR). This is simply for have standard commit messages through the project.

**Pull request closed without merging**
